### ISSUE TITLE
Can't use special characters in LDB search

### ISSUE THREAD

**Issue by svenvanhal** [WISVCH/dienst2#126]
When searching for persons or organizations in ldb, using a special character generates a 500 Internal Server Error.

Details:
```
Internal Server Error: /dienst2/ldb/people/search/
Traceback (most recent call last):
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_django.py", line 872, in wrapper
    return wrapped(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/generic/base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/srv/www/dienst2/ldb/views.py", line 78, in get
    return super(ResultsView, self).get(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/generic/base.py", line 158, in get
    context = self.get_context_data(**kwargs)
  File "/srv/www/dienst2/ldb/views.py", line 68, in get_context_data
    results = self.get_results()
  File "/srv/www/dienst2/ldb/views.py", line 56, in get_results
    search_term = convert_free_search(q)
  File "/srv/www/dienst2/dienst2/extras.py", line 36, in convert_free_search
    return ' '.join([search_format.format(word) for word in string.split(' ')])
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb1' in position 6: ordinal not in range(128)
```

**Comment by jgadelange** [comment]
Fixed by adding `from __future__ import unicode_literals` to `dienst2/extras.py`
