### ISSUE TITLE
Search is broken in master

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#196]
This message is logged during `pip install`:
```
django-haystack 2.7.0 has requirement Django<1.12,>=1.8, but you'll have django 2.0.5 which is incompatible.
```
The following is logged during container start:
```
 Traceback (most recent call last):
  File "./manage.py", line 10, in &lt;module&gt;
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/haystack/management/commands/rebuild_index.py", line 36, in handle
    call_command('clear_index', **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 133, in call_command
    ', '.join(sorted(valid_options)),
TypeError: Unknown option(s) for clear_index command: batchsize, workers. Valid options are: commit, help, interactive, no_color, nocommit, noinput, pythonpath, settings, skip_checks, stderr, stdout, traceback, using, verbosity, version. 
```

**Comment by praseodym** [comment]
[Should be fixed in Haystack 2.8.0](https://github.com/django-haystack/django-haystack/pull/1582)
