### ISSUE TITLE
Django admin reverse links are broken

### ISSUE THREAD

**Issue by praseodym** [WISVCH/dienst2#63]
"Toon op site" button in Django admin is broken

````
Internal Server Error: /dienst2/admin/r/11/4509/
Traceback (most recent call last):
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/utils/decorators.py", line 145, in inner
    return func(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 499, in wrapper
    return wrapped(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 254, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/contrib/contenttypes/views.py", line 31, in shortcut
    absurl = get_absolute_url()
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/db/models/__init__.py", line 42, in inner
    return reverse(bits[0], None, *bits[1:3])
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 593, in wrapper
    return execute(*args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/newrelic-2.50.0.39/newrelic/hooks/framework_django.py", line 592, in execute
    return wrapped(viewname, *args, **kwargs)
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 579, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/srv/www/dienst2/.dienst2-env/lib/python2.7/site-packages/django/core/urlresolvers.py", line 496, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'ldb_people_detail' with arguments '('$person_id',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []
````

**Comment by jgadelange** [comment]
Comes from an `get_absolute_url` method that does not work anymore since the url does not exist anymore.
